# Generated by Django 3.2.8 on 2022-11-13 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^(((?:\\+|00)964)|(0)*)7\\d{9}$', 'The phone number provided is invalid')]),
            preserve_default=False,
        ),
    ]
