# Generated by Django 3.2.8 on 2022-11-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(blank=True, null=True, verbose_name='total_items'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1000, null=True, verbose_name='total_price'),
        ),
    ]
