# Generated by Django 3.2.8 on 2022-11-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_auto_20221112_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_default_image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(related_name='products', to='commerce.ProductImage', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(related_name='products', to='commerce.ProductSize', verbose_name='Size'),
        ),
    ]
