# Generated by Django 3.2.8 on 2022-11-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_auto_20221114_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='types',
            field=models.ManyToManyField(related_name='categories', to='commerce.ProductType', verbose_name='Types'),
        ),
    ]
