# Generated by Django 3.2.8 on 2022-11-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_alter_category_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='commerce.category', verbose_name='الصنف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف للمنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='الخصم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(related_name='products', to='commerce.ProductImage', verbose_name='الصور'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='أسم المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(related_name='products', to='commerce.ProductSize', verbose_name='الحجم'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='النوع', to='commerce.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.IntegerField(verbose_name='الكية'),
        ),
    ]
